"""message

Revision ID: 084b191ec495
Revises: 1128825a326b
Create Date: 2024-06-30 14:13:45.604967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '084b191ec495'
down_revision = '1128825a326b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
